In [1]:
# Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### We have last year's(365 days price of the bitcoin, based on which we'll predict the next 30 days price of the bitcoin)


In [2]:
data = pd.read_csv('Resources/BitcoinPrice.csv')

In [3]:
data.head()
#data.tail()

Date        Price
0  2018-08-25 00:00:00  6719.429231
1  2018-08-26 00:00:00  6673.274167
2  2018-08-27 00:00:00  6719.266154
3  2018-08-28 00:00:00  7000.040000
4  2018-08-29 00:00:00  7054.276429

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 365 entries, 0 to 364
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Date    365 non-null    object 
 1   Price   365 non-null    float64
dtypes: float64(1), object(1)
memory usage: 5.8+ KB


In [5]:
data.describe()

Price
count    365.000000
mean    6343.278019
std     2578.121880
min     3225.299167
25%     3933.143333
50%     6296.320833
75%     7920.945000
max    12686.388333

In [6]:
data.drop(['Date'],1,inplace=True)
data.head()

Price
0  6719.429231
1  6673.274167
2  6719.266154
3  7000.040000
4  7054.276429

In [7]:
# Prodicting 30 days in future

p_days = 30
data['prediction'] = data[['Price']].shift(-p_days)

In [8]:
data.head()

Price   prediction
0  6719.429231  6639.304167
1  6673.274167  6412.459167
2  6719.266154  6468.631667
3  7000.040000  6535.476667
4  7054.276429  6677.342500

In [9]:
data.tail()

Price  prediction
360  10746.507692         NaN
361  10169.094167         NaN
362  10030.746667         NaN
363  10255.977500         NaN
364  10158.540833         NaN

In [18]:
X = np.array(data.drop(['prediction'],1))

In [19]:
X = X[: len(data)-p_days]

In [22]:
X.shape


(335, 1)

In [23]:
y = np.array(data['prediction'])
y=y[: -p_days]

In [24]:
y.shape

(335,)

In [25]:
# Splitting the data to train and test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [26]:
P_days_array = np.array(data.drop(['prediction'],1))[-p_days:]

In [27]:
P_days_array

array([[ 9774.2575    ],
       [ 9725.4025    ],
       [ 9500.32416667],
       [ 9533.97933333],
       [ 9539.7125    ],
       [ 9873.81166667],
       [10088.8       ],
       [10478.90166667],
       [10790.63      ],
       [10826.275     ],
       [11713.16166667],
       [11759.01916667],
       [11703.73833333],
       [11803.88833333],
       [11816.9125    ],
       [11586.1725    ],
       [11377.80416667],
       [11397.80166667],
       [11144.38916667],
       [10450.81333333],
       [ 9988.9475    ],
       [10230.73333333],
       [10292.38333333],
       [10295.1175    ],
       [10605.82583333],
       [10746.50769231],
       [10169.09416667],
       [10030.74666667],
       [10255.9775    ],
       [10158.54083333]])

In [28]:
# Model Building
from sklearn.ensemble import RandomForestRegressor
Rf = RandomForestRegressor(n_estimators = 1000, random_state = 1)
Rf.fit(X_train,y_train)
print('Random Forest Accuracy : {:.2f}%'.format(Rf.score(X_test,y_test)*100))

Random Forest Accuracy : 82.37%


In [29]:
# Prediction
Rf_predict = Rf.predict(X_test)
Rf_predict

array([10099.64855288,  6413.15468635,  5422.46473583,  4826.22179667,
        3733.56906167, 11027.51929333,  5112.92724583,  3626.21182917,
        3651.32659583,  5384.28998833,  5552.36130455,  4519.31894821,
        3956.63019   ,  4322.90360583,  4025.95995049, 10336.28507551,
        4299.39988487,  3797.185683  ,  4015.95953167,  3818.48781756,
        6508.18958417,  3837.97793923,  5620.67113301,  9194.60565801,
        6071.68250083, 10131.86211013,  8083.0508275 , 10608.48934596,
        6711.23091827,  3813.75996875,  4723.79573481, 11110.7309166 ,
        3900.20828   ,  3872.7821575 ,  4547.9154475 ,  6712.32698494,
        3703.03701481,  3715.58681833,  5073.7961775 ,  4321.37078622,
        5384.6419675 , 10728.29500526,  4476.28942312,  5026.60395679,
        4445.5883425 ,  4213.30108917,  4563.6620675 , 10203.089825  ,
        6177.63344833, 10218.98949083,  6276.76936583, 11614.99932455,
       10302.87836167,  6491.1259335 ,  3483.53979   ,  4322.46326   ,
      

In [30]:
y_test

array([10158.54083333,  6260.53083333,  6176.155     ,  5262.36333333,
        3905.05833333,  9725.4025    ,  5305.275     ,  3406.82083333,
        3604.1175    ,  5274.14583333,  6488.82583333,  3589.26083333,
        3865.7975    ,  3910.97333333,  4107.34083333,  9160.0675    ,
        3458.70333333,  3634.77      ,  3454.00882353,  3813.88      ,
        6412.45916667,  3863.33333333,  3523.96      ,  8721.645     ,
        6309.45285714, 10088.8       ,  8046.10769231, 11314.76153846,
        8063.89583333,  3468.305     ,  3961.49333333,  9346.0725    ,
        3948.41166667,  3812.58583333,  6581.48666667,  7979.575     ,
        3406.7625    ,  3624.15583333,  5114.85416667,  5421.52666667,
        5214.57416667, 10748.01166667,  4011.36583333,  5031.475     ,
        6596.61833333,  3743.905     ,  6299.39916667, 10569.305     ,
        8546.17166667, 10255.9775    ,  7848.41583333, 10300.4875    ,
       11759.01916667,  6498.48583333,  3567.47      ,  4015.60916667,
      

In [31]:
# Model predicion for 30 days
Rf_predict_30 = Rf.predict(P_days_array)
Rf_predict_30

array([10203.089825  , 10199.65718833, 10264.00778333, 10264.00778333,
       10264.00778333, 10113.20385019, 10200.61780929, 10294.01961378,
       10133.33886833, 10123.4644275 , 10035.66870683, 10866.7085525 ,
       10035.66870683, 11223.55679733, 11223.55679733, 11181.14739417,
       11464.0447675 , 11464.0447675 , 10629.57425833, 10244.36642045,
       10096.33592205, 10081.97139429, 10131.86211013, 10131.86211013,
       10615.89652365, 10147.99230833, 10200.61780929, 10099.64855288,
       10115.23977596, 10200.61780929])